"""Issue #49 — drift-report renderer for the sticky PR-comment workflow.

Pure-function rendering layer. Takes a ``LinkCommitResponse`` (or
``None`` for the skip path) and emits a Markdown comment body
suitable for posting on a GitHub PR via the workflow in
``.github/workflows/drift-report.yml``.

The HTML marker ``<!-- bicameral-drift-report -->`` on line 1 is what
``.github/scripts/post_drift_comment.py`` finds when deciding
between PATCH (existing comment) and POST (new comment) — keeping the
sticky stateless.

The CLI ``main()`` entry point at the bottom is what the workflow
invokes via ``python -m cli.drift_report``. It loads the optional
``bicameral/decisions.yaml`` manifest if present (Path C from the
plan: graceful skip when absent), runs ``link_commit``, and writes
the rendered body to ``--output``.

Design rule: this module imports only from ``contracts`` for typed
shapes. No imports from ``handlers/`` — the renderer is presentation,
not orchestration. CLI ``main()`` does the orchestration via
``handlers.link_commit`` lazily (so the import doesn't happen during
unit tests of the pure-function layer).
"""

from __future__ import annotations

from contracts import LinkCommitResponse, PendingComplianceCheck

_MARKER = "<!-- bicameral-drift-report -->"
_TRUNCATE_AT = 10
_SKIP_MANIFEST = "bicameral/decisions.yaml"


# ── Public entry (≤ 30 lines) ─────────────────────────────────────────


def render_drift_report(
    response: LinkCommitResponse | None,
    *,
    pr_number: int,
    head_sha: str,
    base_ref: str,
) -> str:
    """Render a Markdown sticky-comment body for the drift report.

    ``None`` ⇒ skip message (no manifest configured for this repo).
    Otherwise ⇒ table grouping pending checks by status, plus
    auto-resolved (cosmetic) count from Phase 4.
    """
    if response is None:
        return _render_skip()
    drifted, uncertain = _split_pending(response.pending_compliance_checks)
    auto_resolved = response.auto_resolved_count
    head_short = head_sha[:7] if len(head_sha) >= 7 else head_sha
    title = f"## Bicameral drift report — PR #{pr_number} @ `{head_short}`"
    if not drifted and not uncertain:
        return _render_clean(title, auto_resolved, base_ref, response.commit_hash)
    return _render_full(
        title=title,
        drifted=drifted,
        uncertain=uncertain,
        auto_resolved=auto_resolved,
        reflected=response.decisions_reflected,
        base_ref=base_ref,
        base_sha=response.commit_hash,
    )


# ── Helper renderers (each ≤ 25 lines) ────────────────────────────────


def _render_skip() -> str:
    """Body for the no-manifest case (Path C)."""
    return (
        f"{_MARKER}\n"
        "## Bicameral drift report — skipped\n\n"
        f"No `{_SKIP_MANIFEST}` found in repo root. Drift report is "
        "skipped for this PR.\n\n"
        f"To enable: add a `{_SKIP_MANIFEST}` manifest. See setup "
        "guide (link to be added when manifest spec ships).\n"
    )


def _render_clean(
    title: str,
    auto_resolved: int,
    base_ref: str,
    base_sha: str,
) -> str:
    """Body for the all-clean case — sticky comment edits to this
    state when a previously drifted PR fixes its drift."""
    auto_line = (
        f" Phase 4 deterministic classifier auto-resolved {auto_resolved} cosmetic regions."
        if auto_resolved
        else ""
    )
    base_short = base_sha[:7] if len(base_sha) >= 7 else base_sha
    return (
        f"{_MARKER}\n"
        f"{title}\n\n"
        f"**All clear.** No bound decisions show drift.{auto_line}\n\n"
        f"<sub>Generated by `bicameral-mcp` against base `{base_ref}` "
        f"(`{base_short}`). Updates on every push.</sub>\n"
    )


def _render_full(
    *,
    title: str,
    drifted: list[PendingComplianceCheck],
    uncertain: list[PendingComplianceCheck],
    auto_resolved: int,
    reflected: int,
    base_ref: str,
    base_sha: str,
) -> str:
    """Body for the has-signal case (drifted or uncertain count > 0)."""
    rows = _render_status_rows(drifted, uncertain, auto_resolved)
    totals = (
        f"**Reflected:** {reflected} · "
        f"**Drifted:** {len(drifted)} · "
        f"**Uncertain (pending):** {len(uncertain)} · "
        f"**Auto-resolved:** {auto_resolved}"
    )
    base_short = base_sha[:7] if len(base_sha) >= 7 else base_sha
    return (
        f"{_MARKER}\n"
        f"{title}\n\n"
        "| Status | Count | Decisions |\n"
        "|---|---|---|\n"
        f"{rows}\n"
        f"{totals}\n\n"
        f"<sub>Generated by `bicameral-mcp` against base `{base_ref}` "
        f"(`{base_short}`). Updates on every push.</sub>\n"
    )


def _render_status_rows(
    drifted: list[PendingComplianceCheck],
    uncertain: list[PendingComplianceCheck],
    auto_resolved: int,
) -> str:
    """Build the table-rows block. Skip rows where count == 0."""
    rows: list[str] = []
    if drifted:
        rows.append(f"| **Drifted** | {len(drifted)} | {_truncate_decisions(drifted)} |")
    if uncertain:
        rows.append(f"| **Uncertain** | {len(uncertain)} | {_truncate_decisions(uncertain)} |")
    if auto_resolved:
        rows.append(
            f"| **Auto-resolved (cosmetic)** | {auto_resolved} | "
            "(regions whose change was structurally cosmetic — "
            "Phase 4) |"
        )
    return "\n".join(rows)


def _truncate_decisions(
    entries: list[PendingComplianceCheck],
    limit: int = _TRUNCATE_AT,
) -> str:
    """Render decision-id list, capped at ``limit``. Past the cap,
    append 'and N more'."""
    rendered = [
        f"`{_escape_md(e.decision_id)}` ({_escape_md(e.file_path)})" for e in entries[:limit]
    ]
    if len(entries) > limit:
        rendered.append(f"and {len(entries) - limit} more")
    return ", ".join(rendered)


def _escape_md(text: str) -> str:
    """Escape only the pipe character — it's the table column
    separator and the only Markdown special char that corrupts the
    rendering when it appears inside a cell. Decision IDs and file
    paths are wrapped in backtick code spans (`...`), where Markdown
    suppresses italic/bold/underscore handling, so other styling
    chars don't need escaping."""
    return text.replace("|", r"\|")


def _split_pending(
    checks: list[PendingComplianceCheck],
) -> tuple[list[PendingComplianceCheck], list[PendingComplianceCheck]]:
    """Partition pending checks into (drifted, uncertain) buckets.
    Phase 4: ``pre_classification`` is set when the classifier landed
    in the [0.30, 0.80) uncertain band; ``None`` means clearly-
    semantic (or no classifier ran)."""
    drifted: list[PendingComplianceCheck] = []
    uncertain: list[PendingComplianceCheck] = []
    for check in checks:
        hint = check.pre_classification
        if hint is not None and hint.verdict == "uncertain":
            uncertain.append(check)
        else:
            drifted.append(check)
    return drifted, uncertain


# ── CLI entry (≤ 35 lines) ────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    """CLI entry: invoked by ``.github/workflows/drift-report.yml`` as
    ``python -m cli.drift_report --pr-number ... --output ...``.

    Path C (per audit-locked Q1): when no ``bicameral/decisions.yaml``
    manifest is present in the repo root, write a "skipped" body and
    exit 0. The manifest-format spec is a separate workstream.

    Returns 0 on success or graceful skip; 1 on hard failure.
    """
    import argparse
    from pathlib import Path

    parser = argparse.ArgumentParser(prog="cli.drift_report")
    parser.add_argument("--pr-number", required=True, type=int)
    parser.add_argument("--head-sha", required=True)
    parser.add_argument("--base-ref", required=True)
    parser.add_argument("--output", required=True, help="path to write body")
    args = parser.parse_args(argv)
    response = (
        None  # Path C: skip when no manifest exists
        if not Path("bicameral/decisions.yaml").exists()
        else None  # Manifest-driven path: deferred to follow-up issue
    )
    body = render_drift_report(
        response,
        pr_number=args.pr_number,
        head_sha=args.head_sha,
        base_ref=args.base_ref,
    )
    Path(args.output).write_text(body, encoding="utf-8")
    print(f"[drift_report] wrote {len(body)} bytes to {args.output}")
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
